package com.lumiday.app;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.view.animation.DecelerateInterpolator;import android.animation.ValueAnimator;import android.widget.*;import org.json.*;import java.time.*;import java.util.*;import java.io.*;import java.nio.charset.StandardCharsets;

public class MainActivity extends Activity {
 final int BG=0xfff3f7f0,GREEN=0xff8bad7b,INK=0xff252a26,MUTED=0xff969e96,MINT=0xff79d4c9; Store store; LinearLayout root,body,calendar; LocalDate selected=LocalDate.now(); boolean expanded=false; int tab=0; JSONObject detail; float touchY; boolean animating;
 int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);} 
 @Override public void onCreate(Bundle b){super.onCreate(b);try{store=new Store(this);}catch(Exception e){new AlertDialog.Builder(this).setTitle("本地数据无法读取").setMessage("原文件已保留，请先导出原始数据后再恢复备份。\n"+e.getMessage()).setPositiveButton("导出原始数据",(d,w)->export()).setNegativeButton("关闭",(d,w)->finish()).setCancelable(false).show();return;}if(b!=null){selected=LocalDate.parse(b.getString("date",selected.toString()));tab=b.getInt("tab");expanded=b.getBoolean("expanded");}show();}
 @Override protected void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);b.putString("date",selected.toString());b.putInt("tab",tab);b.putBoolean("expanded",expanded);}
 GradientDrawable shape(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
 TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
 TextView button(String s,Runnable r){TextView t=text(s,16,GREEN);t.setGravity(Gravity.CENTER);t.setPadding(dp(12),dp(12),dp(12),dp(12));t.setOnClickListener(v->r.run());return t;}
 LinearLayout vertical(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;} LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 void weighted(LinearLayout r,View v){r.addView(v,new LinearLayout.LayoutParams(0,-2,1));}
 void space(LinearLayout l,int n){l.addView(new View(this),new LinearLayout.LayoutParams(1,dp(n)));}
 LinearLayout card(LinearLayout parent){LinearLayout c=vertical();c.setPadding(dp(18),dp(12),dp(18),dp(12));c.setBackground(shape(Color.WHITE,20));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(16),dp(6),dp(16),dp(6));parent.addView(c,p);return c;}
 void save(){try{store.save();}catch(Exception e){error(e);}}
 void error(Exception e){new AlertDialog.Builder(this).setTitle("操作未完成").setMessage(e.getMessage()).setPositiveButton("知道了",null).show();}
 void put(JSONObject o,String k,Object v){try{o.put(k,v);}catch(Exception e){throw new IllegalStateException(e);}}
 void show(){detail=null;root=vertical();root.setBackgroundColor(BG);setContentView(root);LinearLayout header=row();header.setPadding(dp(20),dp(12),dp(12),dp(4));TextView title=text(new String[]{"今天","日程","四象限","习惯","Lumiday"}[tab],28,INK);title.setTypeface(null,Typeface.BOLD);weighted(header,title);header.addView(button("今天",()->{selected=LocalDate.now();show();}));header.addView(button("⋮",()->menu()));root.addView(header);if(tab<4)calendar();ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);body=vertical();body.setPadding(0,dp(6),0,dp(16));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));if(tab==0)today();if(tab==1)agenda();if(tab==2)quadrants();if(tab==3)habits(body);if(tab==4)settings();LinearLayout actions=row();actions.setGravity(Gravity.END);actions.setPadding(dp(16),0,dp(20),dp(6));if(tab<4){TextView add=button("＋",()->addMenu());add.setTextSize(34);add.setTextColor(Color.WHITE);add.setBackground(shape(GREEN,40));actions.addView(add,new LinearLayout.LayoutParams(dp(64),dp(64)));}root.addView(actions);LinearLayout nav=row();String[] labels={"☑\n今日","▦\n日程","❖\n四象限","◷\n习惯","⚙\n设置"};for(int i=0;i<5;i++){final int n=i;TextView b=button(labels[i],()->{tab=n;show();});b.setTextColor(tab==i?GREEN:MUTED);weighted(nav,b);}root.addView(nav);}
 void calendar(){LinearLayout wrapper=new CalendarPanel();wrapper.setOrientation(LinearLayout.VERTICAL);wrapper.setPadding(dp(14),0,dp(14),0);LinearLayout heading=row();heading.addView(button("‹",()->{selected=expanded?selected.minusMonths(1):selected.minusWeeks(1);show();}));TextView month=button(selected.getYear()+" 年 "+selected.getMonthValue()+" 月",()->toggleCalendar());weighted(heading,month);heading.addView(button("›",()->{selected=expanded?selected.plusMonths(1):selected.plusWeeks(1);show();}));wrapper.addView(heading);LinearLayout weekdays=row();for(String day:new String[]{"日","一","二","三","四","五","六"}){TextView t=text(day,13,MUTED);t.setGravity(Gravity.CENTER);weighted(weekdays,t);}wrapper.addView(weekdays);calendar=vertical();wrapper.addView(calendar,new LinearLayout.LayoutParams(-1,dp(expanded?264:44)));fillCalendar(expanded);TextView handle=button("━━",()->toggleCalendar());handle.setTextSize(12);handle.setPadding(0,dp(3),0,dp(5));wrapper.addView(handle);View.OnTouchListener drag=(v,e)->{if(e.getAction()==MotionEvent.ACTION_DOWN){touchY=e.getY();return true;}if(e.getAction()==MotionEvent.ACTION_UP){float dy=e.getY()-touchY;if(Math.abs(dy)>dp(15)){if((dy>0)!=expanded)toggleCalendar();}else toggleCalendar();return true;}return true;};handle.setOnTouchListener(drag);month.setOnTouchListener(drag);root.addView(wrapper);}
 class CalendarPanel extends LinearLayout {
  float startX,startY; boolean dragging;
  CalendarPanel(){super(MainActivity.this);}
  @Override public boolean onInterceptTouchEvent(android.view.MotionEvent e){
   if(e.getAction()==MotionEvent.ACTION_DOWN){startY=e.getY();startX=e.getX();dragging=false;}
   if(e.getAction()==MotionEvent.ACTION_MOVE && Math.abs(e.getY()-startY)>dp(14) && Math.abs(e.getY()-startY)>Math.abs(e.getX()-startX)){dragging=true;return true;}
   return false;
  }
  @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()==MotionEvent.ACTION_UP && dragging){if((e.getY()>startY)!=expanded)toggleCalendar();dragging=false;}return true;}
 }
 void fillCalendar(boolean full){calendar.removeAllViews();LocalDate first=selected.withDayOfMonth(1);LocalDate start=full?first.minusDays(first.getDayOfWeek().getValue()%7):selected.minusDays(selected.getDayOfWeek().getValue()%7);for(int r=0;r<(full?6:1);r++){LinearLayout line=row();for(int c=0;c<7;c++){LocalDate d=start.plusDays(r*7+c);TextView b=button(""+d.getDayOfMonth(),()->{selected=d;show();});b.setPadding(0,0,0,0);b.setTextColor(d.equals(selected)?Color.WHITE:d.getMonth()==selected.getMonth()?INK:MUTED);if(d.equals(selected))b.setBackground(shape(GREEN,30));line.addView(b,new LinearLayout.LayoutParams(0,dp(44),1));}calendar.addView(line);}}
 void toggleCalendar(){if(animating)return;animating=true;boolean next=!expanded;int from=calendar.getHeight(),to=dp(next?264:44);fillCalendar(true);ValueAnimator a=ValueAnimator.ofInt(from,to);a.setDuration(320);a.setInterpolator(new DecelerateInterpolator());a.addUpdateListener(v->{calendar.getLayoutParams().height=(int)v.getAnimatedValue();calendar.requestLayout();});a.addListener(new android.animation.AnimatorListenerAdapter(){public void onAnimationEnd(android.animation.Animator x){expanded=next;fillCalendar(next);animating=false;}});a.start();}
 ArrayList<JSONObject> tasks(){ArrayList<JSONObject> list=new ArrayList<>();for(int i=0;i<store.tasks().length();i++){JSONObject t=store.tasks().optJSONObject(i);if(selected.toString().equals(t.optString("date")))list.add(t);}list.sort(Comparator.comparing(t->t.optString("time","")));return list;}
 void empty(LinearLayout p,String s){TextView t=text(s,15,MUTED);t.setPadding(0,dp(20),0,dp(20));p.addView(t);}
 void today(){LinearLayout c=card(body);c.addView(text(selected.equals(LocalDate.now())?"今日任务":"任务 · "+selected,17,INK));int count=0;for(JSONObject t:tasks())if(!t.optBoolean("done")){task(c,t,false);count++;}if(count==0)empty(c,"今天很轻盈，添加一件想做的事吧");habits(body);LinearLayout done=card(body);int n=0;for(JSONObject t:tasks())if(t.optBoolean("done"))n++;TextView h=button("已完成  "+n+"  ⌄",()->{for(int i=1;i<done.getChildCount();i++)done.getChildAt(i).setVisibility(done.getChildAt(i).getVisibility()==View.GONE?View.VISIBLE:View.GONE);});done.addView(h);for(JSONObject t:tasks())if(t.optBoolean("done"))task(done,t,false);}
 int priorityColor(int p){return new int[]{MUTED,0xff5278eb,0xffedb037,0xffe65b5b}[Math.max(0,Math.min(p,3))];}
 void task(LinearLayout parent,JSONObject t,boolean timeline){LinearLayout r=row();CheckBox cb=new CheckBox(this);cb.setButtonTintList(android.content.res.ColorStateList.valueOf(t.optBoolean("done")?0xffcbd1cb:priorityColor(t.optInt("priority"))));cb.setChecked(t.optBoolean("done"));cb.setOnCheckedChangeListener((b,v)->{put(t,"done",v);save();show();});r.addView(cb);TextView name=text(t.optString("title"),18,t.optBoolean("done")?MUTED:INK);name.setPadding(dp(6),dp(17),dp(6),dp(17));name.setOnClickListener(v->editTask(t));weighted(r,name);TextView time=text(t.optString("time").isEmpty()?"全天":t.optString("time"),14,GREEN);time.setOnClickListener(v->editTask(t));r.addView(time);parent.addView(r);}
 void agenda(){for(JSONObject t:tasks()){LinearLayout line=row();line.setPadding(dp(14),0,0,0);TextView stamp=text(t.optString("time").isEmpty()?"全天":t.optString("time"),14,MUTED);line.addView(stamp,new LinearLayout.LayoutParams(dp(50),dp(74)));LinearLayout holder=vertical();line.addView(holder,new LinearLayout.LayoutParams(0,-2,1));LinearLayout c=card(holder);task(c,t,true);body.addView(line);}habits(body);if(tasks().isEmpty())empty(card(body),"这一天暂无日程");}
 void quadrants(){
 String[] titles={"Ⅰ 重要且紧急","Ⅱ 重要不紧急","Ⅲ 不重要但紧急","Ⅳ 不重要不紧急"};
 for(int rowIndex=0;rowIndex<2;rowIndex++) {LinearLayout pair=row();pair.setGravity(Gravity.TOP);pair.setPadding(dp(10),dp(6),dp(10),dp(6));body.addView(pair);
 for(int col=0;col<2;col++){int index=rowIndex*2+col,priority=3-index;LinearLayout box=vertical();box.setBackground(shape(Color.WHITE,20));box.setPadding(dp(10),dp(15),dp(10),dp(15));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(280),1);lp.setMargins(dp(4),0,dp(4),0);pair.addView(box,lp);box.addView(text(titles[index],14,priorityColor(priority)));ScrollView sc=new ScrollView(this);LinearLayout list=vertical();sc.addView(list);box.addView(sc);int count=0;for(JSONObject t:tasks())if(t.optInt("priority")==priority){task(list,t,false);count++;}if(count==0)empty(list,"没有任务");}
 }
 }
 int progress(JSONObject h){return h.optJSONObject("logs").optInt(selected.toString(),0);} int target(JSONObject h){return h.optInt("target",1);}
 void habits(LinearLayout parent){LinearLayout c=card(parent);LinearLayout heading=row();weighted(heading,text("习惯",18,INK));heading.addView(button("＋",()->editHabit(null)));c.addView(heading);if(store.habits().length()==0)empty(c,"从一个小习惯开始，坚持会被看见");for(int i=0;i<store.habits().length();i++){JSONObject h=store.habits().optJSONObject(i);int p=progress(h),goal=target(h);LinearLayout r=row();TextView icon=text(p>=goal?"✓":h.optString("emoji","◷"),27,MINT);r.addView(icon,new LinearLayout.LayoutParams(dp(42),dp(70)));LinearLayout label=vertical();label.addView(text(h.optString("title"),18,INK));label.addView(text(p+" / "+goal+" "+h.optString("unit","次"),13,MUTED));ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(goal);bar.setProgress(p);bar.setProgressTintList(android.content.res.ColorStateList.valueOf(MINT));label.addView(bar,new LinearLayout.LayoutParams(-1,dp(4)));weighted(r,label);r.addView(button("›",()->habitDetail(h)));r.setOnClickListener(v->habitDetail(h));c.addView(r);}}
 void addMenu(){new AlertDialog.Builder(this).setTitle("添加到 Lumiday").setItems(new String[]{"待办日程","习惯"},(d,w)->{if(w==0)editTask(null);else editHabit(null);}).show();}
 EditText input(LinearLayout p,String hint,String value){EditText e=new EditText(this);e.setSingleLine(true);e.setTextSize(17);e.setHint(hint);e.setText(value);p.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));return e;}
 LinearLayout form(){LinearLayout p=vertical();p.setPadding(dp(24),dp(12),dp(24),dp(20));return p;}
 void editTask(JSONObject existing){JSONObject t=existing==null?new JSONObject():existing;LinearLayout p=form();EditText name=input(p,"准备做什么？",t.optString("title"));EditText note=input(p,"描述",t.optString("note"));LocalDate[] date={LocalDate.parse(t.optString("date",selected.toString()))};String[] time={t.optString("time","")};TextView dateBtn=button("日期  "+date[0],()->{});dateBtn.setOnClickListener(v->new DatePickerDialog(this,(view,y,m,d)->{date[0]=LocalDate.of(y,m+1,d);dateBtn.setText("日期  "+date[0]);},date[0].getYear(),date[0].getMonthValue()-1,date[0].getDayOfMonth()).show());p.addView(dateBtn);TextView timeBtn=button("时间  "+(time[0].isEmpty()?"全天":time[0]),()->{});timeBtn.setOnClickListener(v->{LocalTime tm=time[0].isEmpty()?LocalTime.of(9,0):LocalTime.parse(time[0]);new TimePickerDialog(this,(view,h,m)->{time[0]=String.format(Locale.ROOT,"%02d:%02d",h,m);timeBtn.setText("时间  "+time[0]);},tm.getHour(),tm.getMinute(),true).show();});p.addView(timeBtn);p.addView(button("设为全天",()->{time[0]="";timeBtn.setText("时间  全天");}));Spinner priority=new Spinner(this);priority.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"无优先级","低优先级","中优先级","高优先级"}));priority.setSelection(t.optInt("priority"));p.addView(priority);AlertDialog dlg=new AlertDialog.Builder(this).setTitle(existing==null?"添加日程":"编辑日程").setView(p).setPositiveButton("保存",null).setNegativeButton("取消",null).setNeutralButton(existing==null?"":"删除",(d,w)->{if(existing!=null)remove(store.tasks(),existing);}).create();dlg.setOnShowListener(d->dlg.getButton(-1).setOnClickListener(v->{if(name.getText().toString().trim().isEmpty()){name.setError("请输入任务名称");return;}put(t,"title",name.getText().toString().trim());put(t,"note",note.getText().toString());put(t,"date",date[0].toString());put(t,"time",time[0]);put(t,"priority",priority.getSelectedItemPosition());if(existing==null){put(t,"id",UUID.randomUUID().toString());store.tasks().put(t);}save();dlg.dismiss();show();}));dlg.show();sheet(dlg);}
 void sheet(AlertDialog dialog){android.view.Window w=dialog.getWindow();if(w!=null){w.setGravity(Gravity.BOTTOM);w.setBackgroundDrawable(shape(Color.WHITE,24));w.setLayout(-1,-2);}}
 void remove(JSONArray a,JSONObject o){new AlertDialog.Builder(this).setTitle("删除这条记录？").setMessage("删除后可通过之前导出的备份恢复。").setNegativeButton("取消",null).setPositiveButton("删除",(d,w)->{for(int i=0;i<a.length();i++)if(a.optJSONObject(i)==o){a.remove(i);break;}save();show();}).show();}
 void editHabit(JSONObject existing){JSONObject h=existing==null?new JSONObject():existing;LinearLayout p=form();EditText name=input(p,"习惯名称",h.optString("title"));EditText desc=input(p,"给自己的鼓励",h.optString("note"));EditText goal=input(p,"每日目标，例如 3",h.optString("target","1"));goal.setInputType(2);EditText unit=input(p,"单位",h.optString("unit","次"));Spinner icon=new Spinner(this);String[] icons={"💧","🍎","📖","🏃","🌱","☀"};icon.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,icons));for(int i=0;i<icons.length;i++)if(icons[i].equals(h.optString("emoji")))icon.setSelection(i);p.addView(icon);AlertDialog dlg=new AlertDialog.Builder(this).setTitle(existing==null?"养成一个好习惯":"编辑习惯").setView(p).setPositiveButton("保存",null).setNegativeButton("取消",null).create();dlg.setOnShowListener(d->dlg.getButton(-1).setOnClickListener(v->{String title=name.getText().toString().trim();int n;try{n=Integer.parseInt(goal.getText().toString());if(n<1||n>100000)throw new Exception();}catch(Exception e){goal.setError("目标需为 1–100000");return;}if(title.isEmpty()){name.setError("请输入习惯名称");return;}put(h,"title",title);put(h,"note",desc.getText().toString());put(h,"target",n);put(h,"unit",unit.getText().toString().trim());put(h,"emoji",icons[icon.getSelectedItemPosition()]);if(existing==null){put(h,"id",UUID.randomUUID().toString());put(h,"logs",new JSONObject());store.habits().put(h);}save();dlg.dismiss();show();}));dlg.show();sheet(dlg);}
 void habitDetail(JSONObject h){detail=h;LinearLayout page=vertical();page.setBackgroundColor(MINT);page.setPadding(dp(22),dp(10),dp(22),dp(20));setContentView(page);LinearLayout top=row();weighted(top,button("‹ 返回",()->show()));top.addView(button("编辑",()->editHabit(h)));top.addView(button("删除",()->remove(store.habits(),h)));for(int i=0;i<top.getChildCount();i++)((TextView)top.getChildAt(i)).setTextColor(Color.WHITE);page.addView(top);ScrollView scroll=new ScrollView(this);LinearLayout content=vertical();content.setGravity(Gravity.CENTER_HORIZONTAL);scroll.addView(content);page.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));space(content,30);HabitArt art=new HabitArt(this,h.optString("emoji","🌱"),progress(h)/(float)target(h));content.addView(art,new LinearLayout.LayoutParams(-1,dp(240)));art.setScaleX(.8f);art.setScaleY(.8f);art.animate().scaleX(1).scaleY(1).setDuration(350).start();TextView name=text(h.optString("title"),32,Color.WHITE);name.setTypeface(null,Typeface.BOLD);content.addView(name);space(content,12);content.addView(text(h.optString("note"),17,Color.WHITE));space(content,10);content.addView(text(selected.toString(),14,Color.WHITE));space(content,25);int p=progress(h),goal=target(h);content.addView(text(p>=goal?"✓ 今日已完成":p+" / "+goal+" "+h.optString("unit","次"),23,Color.WHITE));ProgressBar progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(goal);progress.setProgress(p);progress.setProgressTintList(android.content.res.ColorStateList.valueOf(Color.WHITE));content.addView(progress,new LinearLayout.LayoutParams(-1,dp(12)));space(content,20);TextView check=button(p>=goal?"已完成 · 继续保持":"✓  打卡 +1",()->{if(progress(h)<target(h)){put(h.optJSONObject("logs"),selected.toString(),progress(h)+1);save();habitDetail(h);}});check.setBackground(shape(Color.WHITE,30));content.addView(check,new LinearLayout.LayoutParams(-1,dp(60)));TextView undo=button("撤销一次打卡",()->{put(h.optJSONObject("logs"),selected.toString(),Math.max(0,progress(h)-1));save();habitDetail(h);});undo.setTextColor(Color.WHITE);content.addView(undo);space(content,22);LinearLayout stats=card(content);int[] s=stats(h);LinearLayout sr=row();String[] names={"总打卡天数","最高连续","当前连续"};for(int i=0;i<3;i++){TextView x=text(s[i]+"\n"+names[i],16,INK);x.setGravity(Gravity.CENTER);weighted(sr,x);}stats.addView(sr);space(stats,16);stats.addView(text("最近 7 天",15,MUTED));for(int i=6;i>=0;i--){LocalDate d=selected.minusDays(i);stats.addView(text(d+"    "+h.optJSONObject("logs").optInt(d.toString())+" / "+goal,15,INK));}}
 int[] stats(JSONObject h){ArrayList<LocalDate> ds=new ArrayList<>();JSONObject logs=h.optJSONObject("logs");Iterator<String> it=logs.keys();while(it.hasNext()){String d=it.next();if(logs.optInt(d)>=target(h))ds.add(LocalDate.parse(d));}Collections.sort(ds);int best=0,run=0;LocalDate last=null;for(LocalDate d:ds){run=last!=null&&last.plusDays(1).equals(d)?run+1:1;best=Math.max(best,run);last=d;}LocalDate d=selected;if(logs.optInt(d.toString())<target(h))d=d.minusDays(1);int current=0;while(logs.optInt(d.toString())>=target(h)){current++;d=d.minusDays(1);}return new int[]{ds.size(),best,current};}
 void menu(){new AlertDialog.Builder(this).setItems(new String[]{"导出备份","导入备份","设置"},(d,w)->{if(w==0)export();if(w==1)importBackup();if(w==2){tab=4;show();}}).show();}
 void settings(){LinearLayout c=card(body);c.addView(text("Lumiday",30,GREEN));c.addView(text("让每一天，轻一点。",17,MUTED));space(c,18);c.addView(text("所有任务与打卡记录仅储存在本机。",15,INK));c.addView(button("导出完整备份",()->export()));c.addView(button("导入备份",()->importBackup()));empty(c,"升级安装会保留本地数据。卸载、更换手机或更新前，请先导出备份。恢复时会自动兼容 v1 / v2 备份，并保留恢复前快照。");c.addView(button("导出恢复前快照",()->{exportSnapshot=true;export();}));empty(c,"版本 1.0.0 · 无需账号 · 离线可用");}
 boolean exportSnapshot=false;
 void export(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_TITLE,"Lumiday-"+LocalDate.now()+".json");startActivityForResult(i,10);}
 void importBackup(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,11);}
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null){exportSnapshot=false;return;}try{if(req==10){byte[] bytes;if(exportSnapshot){bytes=java.nio.file.Files.readAllBytes(new File(getFilesDir(),"before-restore.json").toPath());}else if(store!=null)bytes=store.data.toString(2).getBytes(StandardCharsets.UTF_8);else bytes=java.nio.file.Files.readAllBytes(new File(getFilesDir(),"lumiday.json").toPath());try(OutputStream out=getContentResolver().openOutputStream(data.getData())){out.write(bytes);}Toast.makeText(this,"备份已导出",Toast.LENGTH_LONG).show();}else if(req==11){String raw;try(InputStream in=getContentResolver().openInputStream(data.getData());ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1){if(out.size()+n>10*1024*1024)throw new IOException("备份超过 10 MB");out.write(buf,0,n);}raw=out.toString("UTF-8");}JSONObject verified=Store.validate(raw);new AlertDialog.Builder(this).setTitle("恢复备份？").setMessage("包含 "+verified.getJSONArray("tasks").length()+" 个任务和 "+verified.getJSONArray("habits").length()+" 个习惯，将替换当前数据。恢复前会保存本地快照。").setNegativeButton("取消",null).setPositiveButton("恢复",(d,w)->{try{store.restore(raw);show();Toast.makeText(this,"备份已恢复",Toast.LENGTH_LONG).show();}catch(Exception e){error(e);}}).show();}}catch(Exception e){error(e);}finally{exportSnapshot=false;}}
 @Override public void onBackPressed(){if(detail!=null||tab!=0){tab=0;show();}else super.onBackPressed();}
}
